name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      crystal_version:
        type: string
        default: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-22.04, windows-2022, macos-13]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ github.event.inputs.crystal_branch || 'latest' }}

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install openssl pkg-config
          fi

      - name: Test
        run: |
          bats --pretty --timing test
        env:
          WINDOWS_BASE_DIR: "/d/a"
          TERM: dumb

  test_shards:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-22.04, windows-2022, macos-13]
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global column.ui always
          git config --global core.autocrlf false

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Mercurial
        run: .github/scripts/install-mercurial.bash
        continue-on-error: true

      - name: Install Fossil
        run: bash .github/scripts/install-fossil.bash

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Download source
        uses: actions/checkout@v2

      - name: Test
        run: |
          bats -T --pretty test/shards
        env:
          WINDOWS_BASE_DIR: "/d/a"
